fix: missing changeset for v2.0 - damn sym links.. :(

diff --git a/system/etc/init.d/99sediROM_last b/system/etc/init.d/99sediROM_last
--- a/system/etc/init.d/99sediROM_last
+++ b/system/etc/init.d/99sediROM_last
@@ -3,7 +3,7 @@
 #
 # Author:   Thomas Fischer (xdajog) <mail@se-di.de>
 # Desc:		This code is part of sediROM (http://forum.xda-developers.com/showthread.php?t=2789727)
-# Version:  v2.5 (the first digit reflects the sediROM major version when this file has been created/changed/modified)
+# Version:  v2.6 (the first digit reflects the sediROM major version when this file has been created/changed/modified)
 #
 # License:  This code is licensed under the Creative Commons License CC BY-SA 4.0.
 #
@@ -42,6 +42,16 @@ SEDIDIR=/preload/.sediROM
 
 # Indicator file will be added by shutdown script and that requires at least 1 clean shutdown.
 IFLAG=$SEDIDIR/.initialized
+
+# Load sediROM functions
+SFUNC=/system/etc/sediROM/init.func
+. $SFUNC
+if [ $? -ne 0];then
+    echo "$(date +%D_%T) - sediROM($0): ERROR - FUNCTION LIBRARY COULD NOT INCLUDED! ABORTED!" >> /dev/kmsg
+    exit 9
+else
+    echo "$(date +%D_%T) - sediROM($0): function library included successfully." >> /dev/kmsg
+fi
 
 ############################################################
 # ensure that /data is not encrypted and if so we wait until it will
